### ISSUE TITLE
Arduino blocks itself at sensor_vl53l5cx_top.init_sensor()

### ISSUE THREAD

**Issue by angeloov** [stm32duino/VL53L5CX#10]
Hi,
I'm having a problem with your library. I'm using an Arduino Due, the firmware compiles but it gets stuck at setup() and in particular on the sensor_vl53l5cx_top.init_sensor() function (line 102).

The firmware I'm running is at: https://github.com/stm32duino/X-NUCLEO-53L5A1/blob/main/examples/X_NUCLEO_53L5A1_HelloWorld/X_NUCLEO_53L5A1_HelloWorld.ino

The problem seems to be happening when reading the device_id (see image below).

![Schermata 2022-06-17 alle 10 19 20](https://user-images.githubusercontent.com/67197207/174258255-1c02a1fd-7e2e-4061-9d5c-2c3110eb26e2.png)

Any ideas? Thanks in avance :)

**Comment by cparata** [comment]
Hello @angeloov ,
what is your hardware setup? Arduino DUE plus the X-NUCLEO-53L5A1? Are you using also the satellites? If so, try to remove the satellites from the X-NUCLEO-53L5A1. 
Best Regards,
Carlo

**Comment by angeloov** [comment]
Yes I'm using and Arduino Due and the X-NUCLEO-53L5A1. I'm not using any satellites.

The only difference in my firmware is that I substituted `#define DEV_I2C Wire` to `#define DEV_I2C Wire1`

**Comment by cparata** [comment]
Ok thanks. It seems right. Could you try to put the code below before DEV_I2C.begin()?

```
//NOTE: workaround in order to unblock the I2C bus on the Arduino Due
#ifdef ARDUINO_SAM_DUE
   pinMode(71, OUTPUT);
   pinMode(70, OUTPUT);

   for (int i = 0; i<10; i++){
     digitalWrite(70, LOW);
     delay(3);
     digitalWrite(71, HIGH);
     delay(3);
     digitalWrite(70, HIGH);
     delay(3);
     digitalWrite(71, LOW);
     delay(3);
   }
   pinMode(70, INPUT);
   pinMode(71, INPUT);
#endif
//End of workaround
```

Let me know if anything changes.
Best Regards,
Carlo

**Comment by angeloov** [comment]
It still doesn't work.
Now by tying an oscilloscope to the SCL1 pin (pink signal) it always stays high, and I don't know why.

![image](https://user-images.githubusercontent.com/67197207/174305443-479fd7ba-3d5f-449a-ba88-fd577432b224.jpeg)

I'm using MacOS BigSur and Arduino IDE 1.8.13, any ideas?

**Comment by cparata** [comment]
Could you try to get the signals on SCL and SDA pins when the shield is plugged to the Arduino Due after a reset of the board? Just to see the signals on the I2C pins. You don't need the Pull-Up resistors when you plug the shield because they are already mounted on the X-NUCLEO-53L5A1.
Best Regards,
Carlo

**Comment by angeloov** [comment]
Ok I tried using the Wire and Wire1 ports: respectively ports 20, 21 and ports SCL1 and SDA1.

I can read the signals only by using the Wire1 class (see photo below), but the Wire class doesn't seem to be working.

![image](https://user-images.githubusercontent.com/67197207/174547187-35af92ef-7066-4c40-b051-254780706619.jpeg)

**Comment by cparata** [comment]
Hello @angeloov ,
maybe you can zoom in the signals to see better how they seem. Anyway, in the next days I will try to test your setup on my side and I let you know.
Best Regards,
Carlo

**Comment by angeloov** [comment]
Ok. Btw it's the Wire class that works (not the Wire1).

Thanks for your time.
Have a good day

**Comment by cparata** [comment]
Actually, on the Arduino Due the correct I2C instance to use is the Wire1 because it is the one mapped to pins 70 and 71 on the Arduino R3 connector. So, I expect that the code works only with Wire1 on the Arduino Due.
Best Regards,
Carlo

**Comment by angeloov** [comment]
May I ask with which model of Arduino you tested the two libraries (VL53L5CX, X-NUCLEO-53L5A1) when you wrote them?

**Comment by cparata** [comment]
I tested it with Nucleo-F401RE board, that is not an Arduino board but an STM32 based board.
Best Regards,
Carlo

**Comment by cparata** [comment]
Hello @angeloov ,
I was able to debug the issue with Arduino DUE and at the end it seems that Arduino DUE Wire library is not able to manage correctly an I2C buffer size of BUFFER_LENGTH even if it is declared inside the library itself. Decreasing the maximum I2C buffer size to (BUFFER_LENGTH - 2) seems fixing the issue. So I have updated both VL53L5CX and X-NUCLEO-53L5A1 libraries adding the support also to Arduino DUE. Please, try to download the last version of these libraries and see if everything works fine also on your side. I close this issue.
Best Regards,
Carlo

**Comment by angeloov** [comment]
Now it works, thanks so much for your time Carlo :).

Have a good day.
