### ISSUE TITLE
Compilation error for vl53l5cx_buffers.h

### ISSUE THREAD

**Issue by Fin-Glim** [stm32duino/VL53L5CX#8]
I am using VS Code with the Arduino for VS Code plugin also installed. I eventually want to use this with the Arduino Mega 2560. I am unable to compile the sketch. If any other info is useful, please let me know and I can add it. This is the output I am getting:

```
[Starting] Verifying sketch 'examples\VL53L5CX_Sat_Get_Set_Params\VL53L5CX_Sat_Get_Set_Params.ino'
[Warning] Output path is not specified. Unable to reuse previously compiled files. Build will be slower. See README.
Loading configuration...
Initializing packages...
Preparing boards...
Verifying...
In file included from c:\Users\username\Documents\Arduino\VL53L5CX-main\examples\VL53L5CX_Sat_Get_Set_Params\vl53l5cx_api.cpp:41:0:
vl53l5cx_buffers.h:21565:1: error: too many initializers for 'const uint8_t [0] {aka const unsigned char [0]}'
};
^
c:\Users\username\Documents\Arduino\VL53L5CX-main\examples\VL53L5CX_Sat_Get_Set_Params\vl53l5cx_buffers.h:21565:1: sorry, unimplemented: non-trivial designated initializers not supported
c:\Users\username\Documents\Arduino\VL53L5CX-main\examples\VL53L5CX_Sat_Get_Set_Params\vl53l5cx_buffers.h:21565:1: sorry, unimplemented: non-trivial designated initializers not supported
```

**Comment by fpistm** [comment]
Hi, 
Which board you used?
It seems the compiler does not handle this type of ini structure. Note that the library targets only stm32 arch.

**Comment by Fin-Glim** [comment]
The Arduino Mega 2560

**Comment by fpistm** [comment]
The compiler version of the mega does not support this kind of init. It seems it has been introduced since v8 of gcc.

**Comment by Fin-Glim** [comment]
Do you have any suggestions on how I can proceed? (I’m new at this)

**Comment by fpistm** [comment]
> 

Unfortunately no.
avr-gcc version for the Mega 2560 is: `avr-g++ (GCC) 7.3.0`
As stated this kind of init requires at least gcc version  8.x and the library is well tagged to be compatible for stm32 arch.

Maybe @cparata have other input/idea but I don't know how to change the code to properly init those buffers to be compatible with avr arch.

**Comment by cparata** [comment]
Hello,
I guess that there is a limitation with the maximum array size on the Mega that is 32Kbytes. In this library we need to allocate a buffer of 82KBytes to load the firmware in the sensor. So, basically this library is not compatible at all with Mega board.
I'm sorry for that.
Best Regards,
Carlo
