### ISSUE TITLE
Issue while trying to compile: "sorry, unimplemented: non-trivial designated initializers not supported"

### ISSUE THREAD

**Issue by angeloov** [stm32duino/VL53L5CX#9]
Hi,
I get this message when I try compiling using this library.
My code is the example at `https://github.com/stm32duino/X-NUCLEO-53L5A1/blob/main/examples/X_NUCLEO_53L5A1_HelloWorld/X_NUCLEO_53L5A1_HelloWorld.ino`

I get these messages while trying to compile:
`
Arduino: 1.8.15 (Linux), Board: "Arduino Uno"

WARNING: library STM32duino_VL53L5CX claims to run on stm32 architecture(s) and may be incompatible with your current board which runs on avr architecture(s).
In file included from /home/angelo/Arduino/libraries/STM32duino_VL53L5CX/src/vl53l5cx_api.cpp:41:0:
/home/angelo/Arduino/libraries/STM32duino_VL53L5CX/src/vl53l5cx_buffers.h:21564:1: error: too many initializers for 'const uint8_t [0] {aka const unsigned char [0]}'
 };
 ^
/home/angelo/Arduino/libraries/STM32duino_VL53L5CX/src/vl53l5cx_buffers.h:21564:1: sorry, unimplemented: non-trivial designated initializers not supported
/home/angelo/Arduino/libraries/STM32duino_VL53L5CX/src/vl53l5cx_buffers.h:21564:1: sorry, unimplemented: non-trivial designated initializers not supported
/home/angelo/Arduino/libraries/STM32duino_VL53L5CX/src/vl53l5cx_buffers.h:21564:1: sorry, unimplemented: non-trivial designated initializers not supported
/home/angelo/Arduino/libraries/STM32duino_VL53L5CX/src/vl53l5cx_buffers.h:21564:1: sorry, unimplemented: non-trivial designated initializers not supported

exit status 1
Error compiling for board Arduino Uno.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

`

Any ideas? Thanks in advance.

**Comment by fpistm** [comment]
Hi @angeloov 
Unfortunately, as stated by the log, this library is not compatible with avr architecture as avr gcc is too old.
See https://github.com/stm32duino/VL53L5CX/issues/8#issuecomment-1127388699
Duplicated of #8
